run_name: yolo_grpo_real
# Model arguments
model_name_or_path: /mnt/vast/wonsuk.yang/dpo/v6_4_2/beta_0_5_lr_4e-6_cont_ultrafeedback
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: 
  - /mnt/vast/hyungguk/data/grpo/koifeval
  - /mnt/vast/shared_data/allenai/RLVR-Mixed
  # - /mnt/vast/shared_data/allenai/RLVR-Mixed-nomath
  # - /mnt/vast/shared_data/DigitalLearningGmbH/MATH-lighteval

dataset_configs:
- train
# system_prompt: "You are a helpful AI Assistant, designed to provided well-reasoned and detailed responses."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: Qwen-2.5-7B-Simple-RL
# hub_strategy: every_save
learning_rate: 3.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 7
num_train_epochs: 2
output_dir: /mnt/vast/wonsuk.yang/rlvr/beta_0_5_lr_4e-6_ultrafeedback-allenai
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
reward_funcs:
- accuracy
reward_weights:
- 1.0
save_strategy: steps
save_steps: 0.10
seed: 42
warmup_ratio: 0.1
